version: '3'
services:
  jenkins:
    image: jenkins
    extra_hosts:
      - "moby:127.0.0.1"
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home

  web:
    image: nginx:alpine
    extra_hosts:
      - "moby:127.0.0.1"
    ports: 
      - 9000:80
    volumes:
      - ./cng-jenkins-themes/cng-theme:/usr/share/nginx/html:ro
